"""Dataset curation: consistent GM/GZ and tidy assembly of the 6-DOF CSVs.

Realization axis (R3 expansion)
-------------------------------
The canonical dataset of record pools 6 independent wave-phase realizations per
(tonnage, Hs) cell (90 files); r0 carries the published seed and reproduces the
original single-realization distribution. Each curated row therefore carries a
`realization` column in {0..5}. Legacy single-realization filenames (no `_r<idx>`)
default to realization 0 for back-compatibility.

Correctness note
----------------
The simulated motion (phi, theta) in 00_Ref was generated by fishingVessel.m using a
transverse metacentric height GM that is *clamped* at GM_FLOOR (0.30 m). To keep GZ
consistent with the dynamics that produced the motion, we reproduce that exact formula
(including the clamp). We therefore do NOT un-clamp GM for GZ; the clamp is documented
and the discrepancy with the original paper's Table 1 (0.48-0.82) is a curation
correction recorded in the dataset summary. The unclamped variant (GM-floor study)
recomputes GZ with clamp=False to match its own dynamics.
"""
import os
import re
import shutil

import numpy as np
import pandas as pd

from jmse import config

# Capture tonnage, Hs and (optionally) the realization index. Legacy names with no
# `_r<idx>` segment match too and default to realization 0.
_FNAME_RE = re.compile(r"6Dof_(\d+)ton_.*_Hs([\d.]+)(?:_r(\d+))?_withXacc\.csv")
_CURATED_PATH = config.PROCESSED_DIR / "curated.parquet"
_CURATED_SINGLE_PATH = config.PROCESSED_DIR / "curated_single.parquet"
_SUMMARY_PATH = config.PROCESSED_DIR / "T2_dataset_summary.csv"
_COUNTS_PATH = config.PROCESSED_DIR / "T2_realization_counts.csv"
_ROWS_PER_FILE = 5001          # nominal clean length of a non-divergent series

# Data sources: source key -> (config attr holding the raw dir, GZ clamp). The dir is
# resolved against `config` at call time so the unclamped dir stays overridable
# (JMSE_UNCLAMPED_DIR / monkeypatch). The canonical set is the clamped multi set.
_SOURCES = {
    "multi": ("RAW_DATA_DIR_MULTI", True),
    "multi_unclamped": ("RAW_DATA_DIR_MULTI_UNCLAMPED", False),
    "single": ("RAW_DATA_DIR", True),
}


def compute_gm(L: float, B: float, T: float, *, clamp: bool = True) -> float:
    """Transverse GM (m), reproducing fishingVessel.m exactly.

    Parameters mirror the MATLAB hydrostatics: block coeff CB, waterplane coeff CW,
    KG = KG_RATIO * T, Munro-Smith waterplane inertia coefficient.
    """
    Cb, Cw = config.CB, config.CW
    nabla = Cb * L * B * T                       # volume displacement
    Awp = Cw * B * L                             # waterplane area
    KG = config.KG_RATIO * T
    KB = (1.0 / 3.0) * (5.0 * T / 2.0 - nabla / Awp)
    BG = KG - KB
    k_munro_smith = (6.0 * Cw ** 3) / ((1.0 + Cw) * (1.0 + 2.0 * Cw))
    I_T = k_munro_smith * (B ** 3 * L) / 12.0
    BM_T = I_T / nabla
    GM_T = BM_T - BG
    if clamp and GM_T < config.GM_FLOOR:
        GM_T = config.GM_FLOOR
    return GM_T


def _parse_filename(name: str):
    """Return (tonnage, Hs, realization). Realization defaults to 0 (legacy names)."""
    m = _FNAME_RE.match(name)
    if not m:
        raise ValueError(f"Unexpected filename: {name}")
    real = int(m.group(3)) if m.group(3) is not None else 0
    return int(m.group(1)), float(m.group(2)), real


def _curate_source(source: str) -> pd.DataFrame:
    """Assemble all CSVs of one source into a tidy frame with consistent GM/GZ.

    Adds: tonnage, Hs, realization, L, B, T, GM (precise-dim), GZ (recomputed
    canonical), GZ_csv (original column, kept for the rounding-correction report).
    """
    cfg_attr, clamp = _SOURCES[source]
    raw_dir = getattr(config, cfg_attr)        # resolved at call time (overridable)
    frames = []
    for path in sorted(raw_dir.glob("6Dof_*_withXacc.csv")):
        tonnage, Hs, real = _parse_filename(path.name)
        L, B, T = config.VESSELS[tonnage]
        gm = compute_gm(L, B, T, clamp=clamp)
        df = pd.read_csv(path)
        # A few capsize-regime realizations (10 t, Hs 7) diverge: the integrator
        # emits a contiguous all-NaN tail once roll blows up. Drop the NaN rows so
        # each series is its clean, time-contiguous prefix (no straddle/gap downstream).
        if df.isna().any().any():
            df = df.dropna().reset_index(drop=True)
        df["tonnage"] = tonnage
        df["Hs"] = Hs
        df["realization"] = real
        df["L"], df["B"], df["T"] = L, B, T
        df["GM"] = gm
        df["GZ_csv"] = df["GZ"]                       # original (rounded-dim) value
        df["GZ"] = gm * np.sin(df["Xacc"])           # canonical, dynamics-consistent
        frames.append(df)
    if not frames:
        raise FileNotFoundError(f"No CSVs found for source '{source}' in {raw_dir}")
    return pd.concat(frames, ignore_index=True)


def build_curated_dataset(force: bool = False, source: str = "multi") -> pd.DataFrame:
    """Build the curated frame for `source`.

    The canonical `multi` (clamped) set is cached at data_processed/curated.parquet;
    on first build the prior single-realization parquet is preserved as
    curated_single.parquet so nothing is lost. Non-canonical sources (e.g. the
    unclamped GM-floor variant) are returned but never cached, so they cannot
    clobber the canonical parquet.
    """
    if source != "multi":
        return _curate_source(source)

    if _CURATED_PATH.exists() and not force:
        return load_curated()

    # Preserve the legacy single-realization parquet exactly once before overwriting.
    if _CURATED_PATH.exists() and not _CURATED_SINGLE_PATH.exists():
        shutil.copy2(_CURATED_PATH, _CURATED_SINGLE_PATH)

    curated = _curate_source("multi")
    config.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    # Atomic write: a concurrent load_curated() never sees a half-written parquet.
    tmp = _CURATED_PATH.with_suffix(".parquet.tmp")
    curated.to_parquet(tmp, index=False)
    os.replace(tmp, _CURATED_PATH)
    return curated


def load_curated() -> pd.DataFrame:
    if not _CURATED_PATH.exists():
        return build_curated_dataset(force=True)
    return pd.read_parquet(_CURATED_PATH)


def realization_counts_report() -> pd.DataFrame:
    """Per-(tonnage, Hs, realization) clean-row counts (-> T2_realization_counts.csv).

    Transparency for the R3 expansion: 3 capsize-regime realizations (10 t, Hs 7) diverge
    and lose their NaN tails in curation, so this table lets reviewers see the uneven
    coverage directly. `n_expected` is the nominal full length (5001); `is_full` flags the
    series that retain it. `n_dropped` is the count of rows lost to simulator divergence.
    """
    df = load_curated()
    rows = []
    for (ton, hs, real), g in df.groupby(["tonnage", "Hs", "realization"]):
        n = len(g)
        rows.append({
            "tonnage": int(ton), "Hs": float(hs), "realization": int(real),
            "n_rows": int(n), "n_expected": _ROWS_PER_FILE,
            "n_dropped": int(_ROWS_PER_FILE - n), "is_full": bool(n == _ROWS_PER_FILE),
        })
    report = pd.DataFrame(rows).sort_values(
        ["tonnage", "Hs", "realization"]).reset_index(drop=True)
    config.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    report.to_csv(_COUNTS_PATH, index=False)
    return report


def dataset_summary() -> pd.DataFrame:
    """Realization-averaged per-(tonnage, Hs) summary table (-> T2_dataset_summary.csv).

    Each Xacc statistic is computed per (tonnage, Hs, realization) and then reduced to
    a mean +/- std across the 6 realizations, so the table reports both the central
    tendency and the wave-phase spread that motivated the multi-realization expansion.
    """
    df = load_curated()
    df = df.assign(_deg=np.degrees(df["Xacc"]))

    # Per-(cell, realization) statistics first.
    per_real = []
    for (ton, hs, real), g in df.groupby(["tonnage", "Hs", "realization"]):
        d = g["_deg"]
        per_real.append({
            "tonnage": ton, "Hs": hs, "realization": real, "N": len(g),
            "GM": float(g["GM"].iloc[0]),
            "Xacc_mean_deg": float(d.mean()),
            "Xacc_std_deg": float(d.std()),
            "Xacc_max_deg": float(d.max()),
            "exceed_15deg_pct": float((d > 15).mean() * 100),
            "exceed_20deg_pct": float((d > 20).mean() * 100),
            "exceed_25deg_pct": float((d > 25).mean() * 100),
        })
    pr = pd.DataFrame(per_real)

    # Reduce across realizations: mean and std (wave-phase spread) per cell.
    stat_cols = ["Xacc_mean_deg", "Xacc_std_deg", "Xacc_max_deg",
                 "exceed_15deg_pct", "exceed_20deg_pct", "exceed_25deg_pct"]
    rows = []
    for (ton, hs), g in pr.groupby(["tonnage", "Hs"]):
        row = {
            "tonnage": ton, "Hs": hs,
            "n_real": int(g["realization"].nunique()),
            "N": int(g["N"].sum()),
            "GM": round(float(g["GM"].iloc[0]), 4),
        }
        for c in stat_cols:
            row[f"{c}_mean"] = round(float(g[c].mean()), 2)
            row[f"{c}_std"] = round(float(g[c].std(ddof=1)), 2) if len(g) > 1 else 0.0
        rows.append(row)
    summary = pd.DataFrame(rows).sort_values(["tonnage", "Hs"]).reset_index(drop=True)
    config.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    summary.to_csv(_SUMMARY_PATH, index=False)
    realization_counts_report()                        # also emit the per-realization coverage table
    return summary
